### ISSUE TITLE
Autoloading wot working for me

### ISSUE THREAD

**Issue by kossa** [Arrilot/laravel-widgets#1]
Hi,
I liked the widget you provide, and I want to use it, very simple and useful, my only problem is the autoloading, I'm working with Laravel 4.2 and laravel-widgets version ~1.0.

I created a widget using `php artisan make:widget StatsDash`, I added to composer.json I have

```
...
"app/database/
"app/tests/TestCase.php"
"app/Widgets/StatsDash.php"
```

I works well, but I want to add the Widgets folder to my project, so I dont need to add each time my new widget, so I used PSR-0

```
"psr-0":{
    "Widgets": "app/",
}
```

after that I used : `composer dumpautoload` I got : 'Class 'App\Widgets\StatsDash' not found'

Thank you for helping

**Comment by arrilot** [comment]
Hi, just add `"app/Widgets"` to the classmap in `composer.json` like that

``` php
    "autoload": {
        "classmap": [
            "app/commands",
            "app/controllers",
            "app/models",
            "app/database/migrations",
            "app/database/seeds",
            "app/tests/TestCase.php",
            "app/Widgets"
        ]
    },
```

That should work well.

**Comment by kossa** [comment]
Alright it works well :D
Thank you again
