### ISSUE TITLE
Real-time widgets

### ISSUE THREAD

**Issue by onbjerg** [Arrilot/laravel-widgets#10]
Is it possible to have real-time(ish) widgets that update every x ms? If not, this would be really cool to add, as it is exactly what I need.

Great package nonetheless, very clean code.

**Comment by arrilot** [comment]
Thanks.
I've never thought about this use case to be honest. It's pretty rare i think.

On the other hand I agree that this could be a great addition, so I'll probably gonna play with this idea in the near future.

**Comment by onbjerg** [comment]
Great! It is pretty common if you want to create a neat dashboard with statistics etc., I think

**Comment by arrilot** [comment]
Implemented in 2.5.0

Check "Reloadable widgets" section in the readme.

**Comment by onbjerg** [comment]
That was fast. Great job!

**Comment by arrilot** [comment]
If you have any other ideas - feel free to share
