### ISSUE TITLE
Auth::user() is null for AsyncWidgets

### ISSUE THREAD

**Issue by m4a1fox** [Arrilot/laravel-widgets#102]
Hi. First of all - thanks for that cool package.

One question. When I'm using @asyncWidget my Auth::user is null, if I use @widget - all works fine.

Is there are a way to make Auth::user working for @asyncWidget request? Thanks.

**Comment by arrilot** [comment]
Hi, what Laravel version do you use?

**Comment by m4a1fox** [comment]
Laravel Framework 5.6.15

**Comment by arrilot** [comment]
Thanks for reporting. Resolved in https://github.com/arrilot/laravel-widgets/releases/tag/3.11.0

**Comment by m4a1fox** [comment]
Same story. I've updated package, http://jmp.sh/6VZmO2r but @asyncWidget saying that \Auth::user() === NULL.

P.S. If that important - Laravel was updated to  5.6.16

**Comment by arrilot** [comment]
Was package config published to your app? If so you need to add 'web' middleware to it

**Comment by m4a1fox** [comment]
Yep. That help. Thanks for advice.
