### ISSUE TITLE
Using widgets with in Vue Templates

### ISSUE THREAD

**Issue by mintunitish** [Arrilot/laravel-widgets#105]
Using the widget puts a script tag and writes the widget there. This is causing issue when I am compiling the Vue templates with webpack. 

It gives error stating "- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed. ".

**Comment by arrilot** [comment]
Async and reloadable widgets are not compatible with vuejs. Write this logic in javascript on your own

**Comment by milanchheda** [comment]
I am getting the same error when using `asyncWidget` or `reloadTimeout`. @mintunitish , were you able to fix or find a workaround for this?

**Comment by mintunitish** [comment]
@milanchheda No I didn't. Eventually I moved completely to vuejs components.
