### ISSUE TITLE
Error on asyncWidgets or reloadable

### ISSUE THREAD

**Issue by mintunitish** [Arrilot/laravel-widgets#107]
Setting a widget asynchronous or re-loadable gives the error
"Trying to get property of non-object". However its working working fine with synchronous widgets with no reloading.

**Comment by arrilot** [comment]
This is a php error. isn't it?
Please make sure you have the latest package version and `web` middleware there https://github.com/arrilot/laravel-widgets/blob/master/src/config/config.php#L11 in your config

If it doesn't help - provide exception trace

**Comment by mintunitish** [comment]
Actually the thing is, since the widgets are re-loadable and do that by sending the AJAX requests. However when accessing data in widgets somehow the ajax calls are not able to get them due to authentication problem.

**Comment by arrilot** [comment]
Right, that's why `web` middleware must be attached in configuration file. It provides session based authorization
