### ISSUE TITLE
Passing models to asyncWidget

### ISSUE THREAD

**Issue by hubertnnn** [Arrilot/laravel-widgets#109]
When I pass a model object to widget, the config array contains the model, 
but if I use the asyncWidget, then I get an array containting model fields, I assume $model->toArray().

Example:
```
@widget('UserStatistics', ['user' => Auth::user()])
@asyncWidget('UserStatistics', ['user' => Auth::user()])
```

I suggest serializing models in the same way as Jobs do it (by serializing only the model id and then loading object from database on deserialization)

**Comment by arrilot** [comment]
I don't want to mess with this kind of stuff because it will lead to some tricky checks and possible security issues.

You can just get a model id from array and load a model yourself in `run` method
