### ISSUE TITLE
[L5] Can't load widgets

### ISSUE THREAD

**Issue by Curdal** [Arrilot/laravel-widgets#11]
When I try to load the widget in my view I get the following error

**
Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Method Illuminate\View\View::__toString() must not throw an exception"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalErrorException in C:\Users\Curtis\Code\laravel\cloudlite\vendor\arrilot\laravel-widgets\src\Factories\AbstractWidgetFactory.php:0

**

**Comment by arrilot** [comment]
There is probably an error in your view.
Check this thread http://stackoverflow.com/questions/21104373/tostring-must-not-throw-an-exception-error-when-using-string

**Comment by Curdal** [comment]
Thanks for that link. It turns out that in the"Widget" Class' the return view statement is the problem

**
return view('widget.tasks');
**

was giving the problem so I just attached the __tostring() method like so
**
return view('widgets.tasks')->__tostring();
**

**Comment by Curdal** [comment]
After some further investigation ... it would seem that there was an error in the view that I wanted to load. After fixing it I removed the "__tostring()" method and it all works fine now.

I'll be sure to use this package a lot. Thank you man (if you even are man)

**Comment by arrilot** [comment]
You are welcome (and yes I'm a man)
