### ISSUE TITLE
widget save in database not executing

### ISSUE THREAD

**Issue by umefarooq** [Arrilot/laravel-widgets#111]
Hi i am widget code through WYSIWYG editor and saving in database, on front end it show same code as it is not calling widget.

`{{ Widget::test() }} //saved in database`

do i need to render page content saved in database first to display main view?

**Comment by sebastienheyd** [comment]
Hi, yes you need to render it with blade before sending the result to the main view, otherwise blade directives are not executed.

**Comment by umefarooq** [comment]
How i can render before sending to main view?

**Comment by arrilot** [comment]
That's a tough question. I don't recommend anyone to do such crazy stuff with widgets.
You can play with `eval` though

**Comment by yajra** [comment]
@umefarooq I like your idea and I think you can achieve this using a middleware and a string search replace. See https://github.com/yajra/laravel-disqus/blob/1.0/src/DisqusMiddleware.php for an idea on how to do it via middleware. Here is how I see implementing this:

1. Add a middleware that will search for `{{ Widget::test() }}`
2. Replace the pattern with the rendered view of the widget (Not yet sure though how to do it.)

I have a personal custom cms and will try to implement your idea when I got the chance.  Thanks!

**Comment by umefarooq** [comment]
well i fond laravel shortcodes work great you save them from database and the work perfect when you call page i really like their view rendering way, now thinking either to go with widgets or shortcodes, here is shortcode package, i am not big fan of wordpress, but you can use wordpress shortcodes with this package.  

https://github.com/webwizo/laravel-shortcodes

now thinking go with widgets or shortcodes.
