### ISSUE TITLE
spatie/laravel-permission Blade directives do not work after install Widget

### ISSUE THREAD

**Issue by Elshaden** [Arrilot/laravel-widgets#112]
Hi

I have installed widget on Laravel 5.6, I had all my spatie permission blade directives working fine before the install, now all my spatie directives just show in the html file as text, without functioning as they should.

could there be a conflict somewhere, or some fix to this, or maybe I should look else where in my code of the problem.

**Comment by arrilot** [comment]
Can't replicate this with L5.5 php 7.2 and latest `arrilot/laravel-widgets` and `spatie/laravel-permission` and `@role` directive

Please make sure that if you uninstall the `arrilot/laravel-widgets` package problems with spatie directives disappear
