### ISSUE TITLE
javascript support 

### ISSUE THREAD

**Issue by slamghost** [Arrilot/laravel-widgets#117]
I need some javascript in my widgets. What is the best way to render the widget including custom js ?

regards

**Comment by arrilot** [comment]
If you use standart widgets (not async and not reloadable) you can use blade's @section to inject javascript to the end of a body

**Comment by oxidand** [comment]
not working, standard widgets, but neither `@section` nor `@push`  are working

**Comment by vsmartcode** [comment]
This may be the solution for you I have tried and succeeded: https://github.com/botble/laravel-assets
