### ISSUE TITLE
@asyncWidget() causing jQuery errors?

### ISSUE THREAD

**Issue by fredbradley** [Arrilot/laravel-widgets#119]
Hello, 

When I load an async widget, the rest of the jQuery on my page breaks? 

with: 

```Uncaught TypeError: jQuery is not a function```

Why might this be? If I remove `@asyncWidget()` and replace for `@widget()` it works fine.

**Comment by arrilot** [comment]
Hi, that's strange. The package does not use jquery at all unless you explicitly turn 'laravel-widgets.use_jquery_for_ajax_calls' to true in config.

Here is a javascript code that is injected when you turn `@widget` to `@asyncWdiget`

https://github.com/arrilot/laravel-widgets/blob/master/src/Factories/JavascriptFactory.php#L139

**Comment by bbredewold** [comment]
Good day!
Looks like this user is using debugbar, which is loaded through the Ajax loaded document...
You have to disable debugbar for these xhr requests, some debugbar logic will be triggered.

I've added a middleware for disabling debugbar on specific routes:
```
if ($request->is('arrilot/*')) {
    Debugbar::disable();
}

return $next($request);
```

**Comment by arrilot** [comment]
Closing it for now then

**Comment by fredbradley** [comment]
Yes - Thank you so much @bbredewold! That makes sense I guess. Frustrating that I could find any info about it. 

@arrilot Could @bbredewold's middleware be added to the package? Or at the very least add this issue to the Readme / install info.

**Comment by noge075** [comment]
> Good day!
> Looks like this user is using debugbar, which is loaded through the Ajax loaded document...
> You have to disable debugbar for these xhr requests, some debugbar logic will be triggered.
> 
> I've added a middleware for disabling debugbar on specific routes:
> 
> ```
> if ($request->is('arrilot/*')) {
>     Debugbar::disable();
> }
> 
> return $next($request);
> ```

If you publish the debugbar config file you can add this route as an "except" parameter.
It's cleaner and never have an error if the package is not installed in production env.
