### ISSUE TITLE
<span> container

### ISSUE THREAD

**Issue by garf** [Arrilot/laravel-widgets#12]
Package adds wrapping span tags like `<span id="arrilot-widget-container-7" class="arrilot-widget-container">` around widget content.
If inside this tags will be placed `<div>` tags, the page becomes invalid for w3c validator.

Maybe it's better use another tags for it?

**Comment by arrilot** [comment]
Gonna think about this in the near future. Thanks for info!

**Comment by arrilot** [comment]
Check https://github.com/Arrilot/laravel-widgets/releases/tag/2.6
