### ISSUE TITLE
Cannot find Class

### ISSUE THREAD

**Issue by Hamarhu** [Arrilot/laravel-widgets#120]
/laravel-widgets
/src
/Factories
/AbstractWidgetFactory.php

Line: 129.

The error is " ErrorException (E_ERROR)
Class "Avisosfases" does not exist (View: xxxxxx/resources/views/home.blade.php)"

It work localy perfect! only gives back error on server!  Can some one give a hint please?

**Comment by arrilot** [comment]
Your widget class can not be autoloaded for some reason.
You can go to AbstractWidgetFactory::instantiateWidget() source code inside vendor directory and try to debug what you get there. The code is pretty simple there
