### ISSUE TITLE
If a user happens to hit an arrilot route

### ISSUE THREAD

**Issue by fredbradley** [Arrilot/laravel-widgets#121]
Hello, 

If a user happens to his an arrilot route (eg. /arrilot/load-widget) it displays "Invalid Payload". Is there a way to produce a nicer message?

![image](https://user-images.githubusercontent.com/1639226/49153470-bdd86500-f30d-11e8-95fe-9f14b15ddfad.png)

**Comment by arrilot** [comment]
Hi, 

with APP_ENV=production and APP_DEBUG=false you should get a general error page with no traces etc
Also it's very unlikely that any user gets there by accident.

**Comment by howdu** [comment]
@arrilot can this error not can be trapped with something simple?

```
public function showWidget(Request $request)
    {
        if (!$request->get('skip_encryption') && !$request->get('params')) return;
```

**Comment by arrilot** [comment]
We should probably respond with `400 bad request` error to such requests.

Feel free to open a PR with the fix if current behavior bothers you.
