### ISSUE TITLE
Error of using the addWidget widget repeatedly

### ISSUE THREAD

**Issue by vsmartcode** [Arrilot/laravel-widgets#126]
When I use addAsyncWidget to group widgets, widgets display well but I get an error when using ajax to reload the widget so I switched to addWidget, but when I switched to addWidget, the error occurred at the widget locations. They all download the first widget :(

![image](https://user-images.githubusercontent.com/4949809/64220686-73b38e00-cef4-11e9-92e8-5df8204c48d1.png)

**Comment by arrilot** [comment]
Noone else reports such problems. Looks like the problem is in your app.
