### ISSUE TITLE
Is it possible that re-loadable widget will reload once? 

### ISSUE THREAD

**Issue by lebroncho** [Arrilot/laravel-widgets#129]
Hello, I'm doing queuing system and I use widgets to reload the page every time there is a number called.

 Inside my widget new_call.blade.php, I put a voice responsive voice code
 `<script type="text/javascript">
	setTimeout(responsiveVoice.speak("{{ $call->letter }}-{{ $call->number }} please proceed to Counter {{ $call->counter_id }}"),5000);
</script>` 

And in my NewCall.php I set with public `$reloadTimeout = 5` that every number was called the voice would speak. I use the reloadTimeout so that every number is called a voice announcer would speak. The problem is the every after 5 seconds the voice would speak. I just want that  the voice would only speak once when every number is called. Is there a possible way that reloadTimeout would only load once and not every N seconds?

**Comment by arrilot** [comment]
There is no way to specify how many times reloadable widget is going to be reloaded.

I suggest you to make widget notreloadable and write reload javascript logic yourself

**Comment by Oxicode** [comment]
> I suggest you to make widget notreloadable and write reload javascript logic yourself

Nooooo, :(
