### ISSUE TITLE
Custom namespaced widget not work with async

### ISSUE THREAD

**Issue by thewebartisan7** [Arrilot/laravel-widgets#133]
I setup in my app Service provider a custom namespace (method `boot()`)

Work with normal `@widget()` but when I try `@asyncWidget()` then I get error class not found.

>  Arrilot \ Widgets \ Misc \ InvalidWidgetClassException
> Class "MyWidget" does not exist

I define namespace like in docs:

`app('arrilot.widget-namespaces')->registerNamespace('custom-namespace', '\Path\To\Widgets');`

And in view:

`@asyncWidget('custom-namespace::mywidget')`

I try also change to `'custom-namespace::MyWidget'`
but it's the same.

All lowercase widget class name work fine using @widget

All work fine with FQCN way, this works:

`@asyncWidget('\Path\To\Widgets\MyWidget')`

Did I missed something or it's a bug?

Laravel 5.8

**Comment by arrilot** [comment]
Sorry for late response. Fixed in 3.13.1
