### ISSUE TITLE
This cache store does not support tagging

### ISSUE THREAD

**Issue by thewebartisan7** [Arrilot/laravel-widgets#134]
In my widget I define cache tag as below:

`public $cacheTags = ['mywidget'];`

When I try to clear cache using:

`Cache::tags('mywidget')->flush();`

Then I get error:

This cache store does not support tagging

The same happen when I try:

`Cache::tags('widgets')->flush();`

Laravel 5.8

**Comment by sebastienheyd** [comment]
https://laravel.com/docs/5.8/cache#cache-tags

> Cache tags are not supported when using the file or database cache drivers. Furthermore, when using multiple tags with caches that are stored "forever", performance will be best with a driver such as memcached, which automatically purges stale records.

You certainly use `file` as cache driver, try with `array`instead by setting it in `.env`...

**Comment by thewebartisan7** [comment]
Thanks! I didn't check into, but most probably you are right.
