### ISSUE TITLE
How to load widget only on user action (e.g. user scroll )

### ISSUE THREAD

**Issue by jrohlandt** [Arrilot/laravel-widgets#135]
Hi, 

I read the docs but can't see if this is possible or not.

We have a very heavy database query that is being run by one of our widgets.
However the widget sits below the fold and it is not likely that each user would even scroll down the page.

So I figure if I can only run the widget when the user scrolls down and the widget is visible then I would save my employer some server resources.

Is something like that possible with this package?

**Comment by sebastienheyd** [comment]
Hello,

What you want to do is a widget lazy loading (like lazy loading for images). 

You can't do that with this package as is, you'll need to make a JS script that will catch the position on the widget container (a div most of the time) on the screen. If the div is visible, you must get the widget content by an ajax call, but you need to develop it this package will not do that for you.

Finally, if the request is heavy but the data are not in real time, maybe you can cache the data and process it via an artisan scheduled task?

**Comment by jrohlandt** [comment]
I didn't think this package supported lazy loading. Thanks for answering @sebastienheyd you saved me a lot of time.

Cheers!
