### ISSUE TITLE
Variable $reloadTimeout can not be used

### ISSUE THREAD

**Issue by ducnx4** [Arrilot/laravel-widgets#137]
It will raise an error with the content show object not found in case of using that variable
Here is the message I got from my project with reloadable widget
 http://localhost/arrilot/load-widget?id=1&name=RecentNews&params=eyJpdiI6IjlWTmxMeVkxZFd2b0YybGVreUwwNkE9PSIsInZhbHVlIjoianBcL1lVTGMyTlplZExrZGh3eWVUTEE9PSIsIm1hYyI6IjIyOTE1NjYzOGM0MDQyOWRkMDZkNDlkMWI4NzIyMjhmNzJjZjU4OGY2NTNmY2RkNmNlNWRlMDYwM2Y3MTNkNGUifQ%3D%3D 404 (Not Found)

**Comment by avinashk369** [comment]
i am getting same error, did you get any solution anyway?

**Comment by avinashk369** [comment]
just to let you know that i uploaded the same code on the live server and it worked without any error.

**Comment by arrilot** [comment]
I've just checked it with Laravel 8 and it works as intented on localhost. It's probably some probablems with your localhost configuration or `use_jquery_for_ajax_calls` is set to true but you do not load Jquery manually (I'll add a note about that)
