### ISSUE TITLE
JavaScript callback on async widget

### ISSUE THREAD

**Issue by buzzclue** [Arrilot/laravel-widgets#143]
Thank you for the wonderful package. 

I have some widgets with lazyload that needs to be updated after widget is loaded. Is there a callback after async widget is loaded?

Thanks

**Comment by buzzclue** [comment]
I used global ajax complete event but I think it will be easier and better if we can add call back on ajax load call.

```javascript
$.ajaxSetup({
    complete: function() {
        myCallback();
     }
 });

**Comment by sebastienheyd** [comment]
Why not reload in a <script> tag directly in your widget view ?

```js
<script>
    if ($.fn.lazy) {
        $('.lazy').lazy();
    }
</script>
```

**Comment by buzzclue** [comment]
My widgets are implemented dynamically and async is optional, although I can check and send the JavaScrcipt but I am not a fan of using inline Javascript. 

![image](https://user-images.githubusercontent.com/43321373/86410777-db816380-bcd4-11ea-8a87-73ef2ba17af2.png)

**Comment by arrilot** [comment]
@sebastienheyd is right widget loading executes all <scripts> inside widget template for this case.

@buzzclue I'm open to a contribution PR that raises smth like a javascript `CustomEvent` on a widget container after ajax call is finished if that's what you are looking for.
