### ISSUE TITLE
Cache forever

### ISSUE THREAD

**Issue by popouille** [Arrilot/laravel-widgets#146]
Hello,
Seems that currently the package doesn't support cacheTime forever?
I tried `public $cacheTime = -1;`
it doesn't work

**Comment by sebastienheyd** [comment]
I wonder what's the point of caching a widget forever. Might as well use a view no ?

**Comment by popouille** [comment]
> I wonder what's the point of caching a widget forever. Might as well use a view no ?

You can cache forever some widget content and invalidate the cache on save or delete, its usefull for some content that is not designed to change many times.

**Comment by arrilot** [comment]
Hello, caching forever is not supported. Just specify a very long ttl (like year) if you need "forever-like" caching behavior
