### ISSUE TITLE
laravel widget async error

### ISSUE THREAD

**Issue by abdullahsayed4131** [Arrilot/laravel-widgets#148]
sir im using your widget package everything is fine until i use async. once i put @asyncWidget('total_count') im getting a error

Request URL: http://localhost/arrilot/load-widget?id=1&name=ItemCount&params=eyJpdiI6IkNBc2FRQ2V2XC9cL1oxMUtyOGhYSDBxUT09IiwidmFsdWUiOiJRbVZUNUYzODRWQnpsTnZSY1wvbnhvQT09IiwibWFjIjoiYmYzYzk2OWVkNTUzYzVhOWQ4M2M5OWIzYjg2Y2I1ZTU3OTRjOGRmNGI2ZjM4OWY3ZTNhMGVmYTM1ZjExYmJhYSJ9
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:80
Referrer Policy: strict-origin-when-cross-origin

i change jquery versions also every version im getting same error
![Capture](https://user-images.githubusercontent.com/37441843/103358733-5092f180-4adc-11eb-9231-751c8fa96405.JPG)

**Comment by arrilot** [comment]
Hello, [here](https://github.com/arrilot/laravel-widgets/blob/master/src/ServiceProvider.php#L68) is how the package registers the route

Please make sure your route cache was cleared after you installed the package
You can then check that the route is registered in the application by running `php artisan route:list`
You can also try dd() in [widget controller](https://github.com/arrilot/laravel-widgets/blob/master/src/Controllers/WidgetController.php#L19) inside your vendor dir to check if the request reaches it

If it's not cache it's probably your app or web server misconfiguration

**Comment by abdullahsayed4131** [comment]
your widgets are working when i used php artisan serve command.. but when i user http://localhost/my_project_name widget getting above error.. even when i uploaded in server with a subdomin there also same problem please give a solution

**Comment by arrilot** [comment]
From the docs 
![image](https://user-images.githubusercontent.com/2826480/103623651-6f184300-4f49-11eb-962f-44e44c49dbca.png)
