### ISSUE TITLE
Error when using Widget group

### ISSUE THREAD

**Issue by ardiansyah** [Arrilot/laravel-widgets#15]
i got an error when using widget group 

```
Class 'Arrilot\Widgets\Misc\Wrapper' not found

```

and i try to inspect your code and found file naming with LaravelApplicationWrapper instead Wrapper, and i change the Class in WidgetGroup.php with LaravelApplicationWrapper.

and also the 
`
appMake() 
`

method that use in WidgetGroup.php on line 112 to 

```
make()
```

i hope you can fix this. 
thanks for the awesome package

**Comment by arrilot** [comment]
Thanks for reporting.
Fixed in 3.0.1
