### ISSUE TITLE
Unable to access Auth::id() in asyncWidget

### ISSUE THREAD

**Issue by imran-drewl** [Arrilot/laravel-widgets#150]
HI @arrilot,

Thanks for this awesome widgets.

I'm facing an issue that when I use normal @widget I can can access authenticated user id in widget blade view using either auth()->user()->id or Auth::id() but not when use **auto-reload** or @asyncWidget.

I'm using laravel 8.*

I didn't published config file.

I have already seen this threat https://github.com/arrilot/laravel-widgets/issues/102

and published config file in project there was already web middleware added in it.

I'm fetching data for widget from an API.

Thanks

**Comment by nabeelio** [comment]
I'm also running into this issue.

**Comment by FatihKoz** [comment]
Same/similar error happens with sync widgets too when `public $reloadTimeout = 60;` is being used ...

```
$user = Auth::user();
$name = $user->name_private;
```

Works just fine during initial run of the widget, but when the auto reload occurs "Trying to get property of non-object" exception is being returned for `$user->name` 'cause the Auth facade call fails or somehow returns null.

**Comment by arrilot** [comment]
I can't repoduce this.

1. I've installed a fresh laravel 8 app using `laravel new`
2. I've Added Laravel Breeze there
3. Registred a user and logged in
4. `composer require arrilot/laravel-widgets`
5. `php artisan make:widget Test`
6. <?php echo time() . " " . auth()->user()->id ?> in the widget's view
7. Placed widget at dashboard
7. Both @widget and @asyncWIdget both give me correct id. If I add $reloadTimeout = 2 they both still work as intented.

My guess: you did somthing with middleware in your apps.
If you can make a similar reproduction and post it to github I can give it another try

**Comment by FatihKoz** [comment]
Yes, it was related with the middleware ... Sorry not reporting that earlier, `web` must be defined/allowed in the middleware for laravel-widgets.

The main app's developer figured it out and with an update to the core app my addon widgets started working as expected.
