### ISSUE TITLE
parseFullWidgetNameFromString breaks namespace with caps and lower case characters

### ISSUE THREAD

**Issue by ngugijames** [Arrilot/laravel-widgets#156]
I have a widget registered under this namespace: **dPOS\Widgets\TestWidget**

But running `@asyncWidget($widget)`, 

Generates the following classname:
**"DPOS\Widgets\TestWidget"**

And hence the exception:
`Class "DPOS\Widgets\TestWidget" does not exist`

This is generated in: https://github.com/arrilot/laravel-widgets/blob/master/src/Factories/AbstractWidgetFactory.php#L170

How can we fix this?

**Comment by arrilot** [comment]
That's unfortunate.

The package follows common (at least in Laravel community) convention to have a namespace in StdulyCase
If you can't change your namespace feel free to send a PR with a configuration option to turn off Str::studly in this line.
