### ISSUE TITLE
PHP 8.2 deprecation error

### ISSUE THREAD

**Issue by u01jmg3** [Arrilot/laravel-widgets#160]
Creation of dynamic property `Arrilot\Widgets\WidgetGroupCollection::$app` is deprecated in `vendor/arrilot/laravel-widgets/src/WidgetGroupCollection.php` on line 23  

https://github.com/arrilot/laravel-widgets/blob/8b0587288cfb301ee4631f381524f82a29341d6b/src/WidgetGroupCollection.php#L23

Solution: https://stackoverflow.com/questions/74878889/php-warning-deprecated-creation-of-dynamic-property-is-deprecated#answer-74879495

**Comment by arrilot** [comment]
Thx, should be resolved in 3.14.0
