### ISSUE TITLE
Can we rearrange folder and file structure

### ISSUE THREAD

**Issue by ducvu91** [Arrilot/laravel-widgets#162]
Hello, can i do this ?
Target : i want each widget is independent, i can copy or move any widget to other project

![image](https://github.com/arrilot/laravel-widgets/assets/19793530/da5dcadd-72bd-4f53-a948-8e8f3d66c56a)

**Comment by arrilot** [comment]
Hello you are free to place widget and view files anywhere in your project as long as they are autoloadable by composer
Use fully qualified class names when you call those widgets https://github.com/arrilot/laravel-widgets#namespaces and make sure that you pass correct path when you call `view()` inside widgets' `run()` methods as well
