### ISSUE TITLE
How can control data in GROUP ?

### ISSUE THREAD

**Issue by ducvu91** [Arrilot/laravel-widgets#166]
Hello,
i have many group, in some case, group is still same data in database. in now, in each widget, it same code, only different in col select.
ex1: widget 1: get col A in table A, widget 2: get col B in table A, widget 3: get col C in table A,  widget 4: get col B in table A, You see, i must do 4 query same, to get same data.
ex2: widget 1,2,3,4 load data default. widget 1 is type select, when widget 1 change data, widget 2,3,4 change by data widget 1
HOW do i control it in group ? if in group i can control data or config, that will return data from group or widget.
Thanks

**Comment by arrilot** [comment]
There is no centralized configuration or data handling for widgets in groups.

The only way to share data between multiple widgets is to fetch the data before running them and pass it using widget configs.
If you pass something mutable (like objects), changes made by one widget will be propagated to others.

This works regardless of whether the widgets are in the same group or not.
