### ISSUE TITLE
container style is loading problem

### ISSUE THREAD

**Issue by wordpress-lab** [Arrilot/laravel-widgets#17]
No change after change style into container function

**Comment by arrilot** [comment]
I don't see any errors with container customization.
Please make sure you use 3.\* version and note that container only appears in async and reloadable widgets

**Comment by wordpress-lab** [comment]
ok boss

**Comment by wordpress-lab** [comment]
may i use @widget('recentNews') into ckeditor............i used .not wordking

**Comment by arrilot** [comment]
I've got no idea how ckeditor works. Do you have any particular errors?

**Comment by wordpress-lab** [comment]
no error

**Comment by wordpress-lab** [comment]
![wid](https://cloud.githubusercontent.com/assets/2592229/8532063/7fdddd8a-244d-11e5-8284-278e078dd491.PNG)

**Comment by arrilot** [comment]
Hmm, are you sure that you call a widget in a blade view? It must have `.blade.php extension`

**Comment by arrilot** [comment]
You can't use `@widget` directive outside blade. Use `Widget::` in this case.

**Comment by wordpress-lab** [comment]
i am using Widget::run('recentNews')

**Comment by wordpress-lab** [comment]
first it will save in database then will show in frontpage

**Comment by wordpress-lab** [comment]
is there any command for all widget list ?

**Comment by wordpress-lab** [comment]
nice project

**Comment by arrilot** [comment]
Nope, there isn't
