### ISSUE TITLE
question about config array

### ISSUE THREAD

**Issue by jhdxr** [Arrilot/laravel-widgets#18]
the example in readme.md says

```
class RecentNews extends AbstractWidget {
    ...
    protected $config = [
        'count' => 5,
        'foo'   => 'bar'
    ];

    ...
}

@widget('recentNews', ['count' => 10]) // $this->config('foo') is still 'bar'
```

however I found some problem.
1. there is no method `config` in `AbstractWidget`. so maybe the last comment should be `// $this->config['foo'] is still 'bar'`
2. I found the example didn't work, so I read the code in `WidgetFactory` and `AbstractWidget`. The params pased to the construct function were set as properties instead of values of confi array. so is the doc out of date or I made some mistake?

**Comment by arrilot** [comment]
1. It's a mistake in the doc, thx
2. Looks like you use 2.\* version. Make sure you have 3.*

**Comment by jhdxr** [comment]
well, yes, I checked my composer.json, and the version there is `^2.6`. It seems 3.0 released 10 days ago so lots of people may be still using 2.x. I think the doc should point out that there is differance betwteen 2.x and 3.x

**Comment by arrilot** [comment]
I don't want to put all those changes in the doc. There are release notes for this specific purpose.

Anyway, I've added a small note in the beginning of the doc. I hope it will prevent ppl from looking into the wrong one.
