### ISSUE TITLE
Widget class must extend Arrilot\Widgets\AbstractWidget class

### ISSUE THREAD

**Issue by bsh314** [Arrilot/laravel-widgets#19]
I was having trouble getting Widgets work on Laravel 5.1. My app runs throw ErrorException, this is it:

```
ErrorException in AbstractWidgetFactory.php line 122:
Widget class must extend Arrilot\Widgets\AbstractWidget class (View: /home/vagrant/Code/Laravel/resources/views/welcome.blade.php)
```

My Widget Class was created with artisan command _'artisan make:widget Input'_
and it extends _AbstractWidget_ from _Arrilot\Widgets\AbstractWidget_. So here is  class:

```
<?php namespace App\Widgets;

use Arrilot\Widgets\AbstractWidget;

class Input extends AbstractWidget {
    protected $config = [
        'type' => 'text'
    ];
    public function run()
    {
        return view("widgets.input", [
            'config' => $this->config,
        ]);
    }
}
```

What can it be? 
Thanks!

**Comment by arrilot** [comment]
How do you call the widget in a view? Looks like you pass something wrong there

**Comment by zorx** [comment]
maybe you already have an **Input** class, because of this :

```
    $widgetClass = class_exists($this->widgetName)
        ? $this->widgetName
        : $rootNamespace.'\\'.$this->widgetName;
```

so if you already have an **Input** class, laravel-widgets will load it and then throw the exception : 

```
    $widget = new $widgetClass($this->widgetConfig);
    if ($widget instanceof AbstractWidget === false) {
        throw new InvalidWidgetClassException();
    }
```

you have to create another widgetName or use namespace in your default **Input** class

**Comment by arrilot** [comment]
huh, In fact that's unexpected.

I've tweaked some stuff to prevent that.

Fixed in 3.1.2

**Comment by arrilot** [comment]
ty for your help @zorx

**Comment by bsh314** [comment]
Thanks @zorx & @arrilot ! Tomorow i'll try to update & post the result!

**Comment by bsh314** [comment]
Yep, **changing Widget Class name is a valid sulution**.
