### ISSUE TITLE
Publish 2 widgets

### ISSUE THREAD

**Issue by kossa** [Arrilot/laravel-widgets#2]
I created 2 widgets, and when I try to display them, I got only one, for example:

```
{{ Widget::widgetOne() }}
{{ Widget::widgetTwo() }}
```

It shows only `widgetOne` , And when I delete the `widgetOne` I can see `widgetTwo`

Why ?

**Comment by arrilot** [comment]
Make sure you don't do anything nasty in the first widgets like `die()`
It works well for me and i can't reproduce your problem

**Comment by kossa** [comment]
Still not working :'(
Here is my project : https://github.com/kossa/moltaka-app/tree/master/app

Please take a look and let me know what happen

**Comment by kossa** [comment]
I created a fresh installation, and alright it works fine, I'll dig again :/

**Comment by kossa** [comment]
I found the problem but not the solution
Please try this : 
1. Create a yield section in your master view : `@yield('content')`
2. in your 2 widgets view use : 

```
@section('content')
some content
@stop
```

You'll see the problem ;)

**Comment by arrilot** [comment]
You overwrite the same blade section.
Use  @parent in your widget view. 
For more info check Laravel doc for blade

**Comment by kossa** [comment]
Ahh alright, Really I don't know that it exists not mentioned : http://laravel.com/docs/4.2/templates#blade-templating

Thank you @Arrilot :+1:

**Comment by arrilot** [comment]
You are welcome

**Comment by ghost** [comment]
Great M.rKossa :)
Your are the master of laravel
And thanks for Mr.Arrilot for his kind support

I like this widget also :)
