### ISSUE TITLE
Base Url

### ISSUE THREAD

**Issue by jooorooo** [Arrilot/laravel-widgets#20]
I have problem. 
my app is installed in folder (http://site.com/folder/) and when called Asynchronous request is send to http://site.com/arrilot/load-widget
Thanks

**Comment by arrilot** [comment]
Well we can't handle all rare cases in configuration.

All you need to do is to copy https://github.com/arrilot/laravel-widgets/blob/master/src/ServiceProvider.php to your app, modify routes, and register it instead of the former one.

I'll note it in the docs too.
