### ISSUE TITLE
Determine if a widget group has anything set

### ISSUE THREAD

**Issue by mastrip2** [Arrilot/laravel-widgets#25]
Is there a way to determine if the widget group has anything set to be displayed? This is a awesome package but it would be nice if you could determine easily if anything is inside the widget group so that maybe something else could be set along with it. I wanted to setup the side bar column widths (using bootstraps col css) if something is inside of the Widget::group('sidebar'). if not than the content area width would be full width.

**Comment by arrilot** [comment]
Gotcha.
1. composer update to get the latest version (3.2.1)
2. Use on of these methods https://github.com/arrilot/laravel-widgets#checking-the-state-of-a-widget-group
