### ISSUE TITLE
Static widgets

### ISSUE THREAD

**Issue by isUndefined** [Arrilot/laravel-widgets#26]
Is it possible to add static widgets without class create?

**Comment by arrilot** [comment]
I can't quite understand what do you mean under "static widget".

Widget class is the place where all the php logic lives. Essentially widget class = widget.
If you don't need any logic you should simply `@include` a view and that's all.

What's your use case?

**Comment by isUndefined** [comment]
`@include` is fixed block without position. In list of widgets `@include` can be at top part or down part of the sidebar but not between.
