### ISSUE TITLE
feature request calling other methods other than run of widget

### ISSUE THREAD

**Issue by umefarooq** [Arrilot/laravel-widgets#27]
Hi, right package widget is calling run method of widget class, can you improve it to call other public method of the same widget, like news widget run is main method which is getting latest news, if we want to get popular news you need to create new widget for popular news, i think no need to create a new widget when news widget is already there just add method popularNews 

`{{ Widget::run('recentNews:popularNews') }}`
or
`{{ Widget::recentNews(['method'=>'popularNews']) }}`
or
`@widget('recentNews:popularNews')`

**Comment by arrilot** [comment]
There are two cases:
1) popularNews and recentNews are very similar. In this case you should use config array to avoid code duplication.
2) If they are too different for #1 you should simply use 2 separate widgets.

So i dont see any need in several run methods. Thanks for proposal, though
