### ISSUE TITLE
Assync container not incrementing the id

### ISSUE THREAD

**Issue by cpgo** [Arrilot/laravel-widgets#28]
When I set a reloadTimeout on my widget it only gets updated once and then I got this error on the js console:

```
Cannot set property 'innerHTML' of null
```

When I inspect the javascript I can see its looking for an element with an id of 'arrilot-widget-container-3' but my widget wrapper is still on 'arrilot-widget-container-2'.

Edit:
I think I was doing something I was not supposed. I had one widget rendering another, that was the source of the error. 
The assync one was the 'parent'.

**Comment by arrilot** [comment]
So, you have the following structure, am I right?
1. Assync widget.
2. In it's view you call another reloadable widget
3. The second widgets loads only once.

I've never thought about nesting all this stuff to be honest, not sure if it's "fixable" :)

**Comment by arrilot** [comment]
Yeah, it's a nofix I'm afraid. Sorry.

I'll add a note about that in the docs.

**Comment by cpgo** [comment]
No worries. I was not planning on using the package like this, just something silly I thought of trying :)
