### ISSUE TITLE
[Enhancement] add a path for stubs

### ISSUE THREAD

**Issue by zorx** [Arrilot/laravel-widgets#29]
Is it possible to add stubs to config file ?

for example 

``` PHP
<?php
return [
    //'default_namespace' => 'App\Widgets',
    'stubs' => [
         'widget' => app_path() . '/vendor/arrilot/laravel-widgets/src/Console/stubs/widget.stub',
         'widget_plain' => app_path() . '/vendor/arrilot/laravel-widgets/src/Console/stubs/widget_plain.stub',
    ],
    'use_jquery_for_ajax_calls' => false,
];
```

it will allow us to customize easily stubs

**Comment by arrilot** [comment]
Do you have a use case where built-in stub is not good enough?

**Comment by arrilot** [comment]
It's not hard to implement but I don't quite see the value of this customization.

**Comment by zorx** [comment]
Right now we can only use a `run` method under the widget class, but in my use case, I would like to have two methods `run` and `setting` because I'm trying to create a system that offers the admin the possiblity to configure the widget from UI.

I know that this package is based only on the `run` method and we can't call another one from outside, that's why I opted for this :

``` PHP
    public function run()
    {
        if (isset($this->config['__setting'])) {
            return $this->setting();
        }else{
            return $this->render();
        }
    }

    protected function render() {
        $config = $this->config;
        // Do something and render

        return view("user.view", compact('config'));
    }

    protected function setting() {
        $config = $this->config;
        // Do something to configure
        return view("admin.view", compact('config'));
    }
```

that's why I have to change stubs

**Comment by arrilot** [comment]
Thanks, makes sense.

Gonna implement it in a couple of days.

**Comment by zorx** [comment]
Awesome thanks

**Comment by arrilot** [comment]
Done in 3.3.
