### ISSUE TITLE
How can I call Widget from controller action ?

### ISSUE THREAD

**Issue by tariqkhatri-gaditek** [Arrilot/laravel-widgets#3]
Calling widget from view for e.g. {!! Widget::recentNews() !!} was successful, but calling Widget::recentNews() gives an error 

<<
Class 'App\Http\Controllers\Widget' not found

Please suggest.

**Comment by arrilot** [comment]
`use Widget;` on top of your controller class to import it.

**Comment by fahadqcns** [comment]
use Widget; not found in my case?

**Comment by arrilot** [comment]
Please make sure you have registered a Widget facade in app/config.php as documentation states.
