### ISSUE TITLE
2 or more AsyncWidget in one place.

### ISSUE THREAD

**Issue by m4a1fox** [Arrilot/laravel-widgets#30]
Hi! I wonder, why it's happens. If I set in blade smth like that:
{{ AsyncWidget::News() }}
{{ AsyncWidget::trendingNow() }}

Render return me in some case only one widget, in some case return me in both widget the same content. Can you help me with it?! Thanks.

FYI: I've set this config: "use_jquery_for_ajax_calls" to true, in this file "vendor/arrilot/laravel-widgets/src/config/config.php" and all works fine now.

**Comment by arrilot** [comment]
Package and Laravel versions please?

**Comment by m4a1fox** [comment]
"laravel/framework": "5.1.*",
"arrilot/laravel-widgets": "^3.3"

**Comment by arrilot** [comment]
Fixed in 3.3.1

Thanks for reporting.
