### ISSUE TITLE
JS reload widget.

### ISSUE THREAD

**Issue by m4a1fox** [Arrilot/laravel-widgets#31]
Hi there. Can I reload any widget via JS or jQuery?

**Comment by arrilot** [comment]
If you need to manually reload the widget just make an ajax call to a new controller action that returns widget content and  do $(el).html(response) in a callback. 

Pretty standart stuff

**Comment by ghost** [comment]
any example for a moron like me ?

**Comment by jerome-savin** [comment]
I would appreciate too 💃
