### ISSUE TITLE
[Enhancement] choose a custom path when creating a widget with make:widget command

### ISSUE THREAD

**Issue by zorx** [Arrilot/laravel-widgets#32]
it would be great if we could change the widgets directory, I think that right now you are using the name space to define in which directory you create a widget, but in my use case the `default_namespace` doesn't reflect the directory

**Example :**

my app is separated into two levels, the core of the application and the custom part

to simplify I have this architecture :

```

./core (which contain laravel project)
  ./app : namespace AppName\
  ./storage 
  ./ ...
./widgets : namespace AppName\Widgets
```

composer helps me to maintain all this things ok, so if I create manually a widget into `./widgets` I can use it without problem, but I can't use the `make:widget`command because it will create a `./core/app/Widgets/RecentNews.php`instead of `./widgets/RecentNews.php`

So the idea is to have the possiblity to choose the path in which we create our widgets.

``` php
<?php

return [
    'default_namespace' => 'App\Widgets',
    /* ... */
    'default_path' => custom_path('widgets'),
];
```

**Comment by arrilot** [comment]
The package follows Laravel's conventions and extends it's generator.
Your case is way too specific imo

I can suggest you to make your own command extending https://github.com/arrilot/laravel-widgets/blob/master/src/Console/WidgetMakeCommand.php and registering it in your own service provider
