### ISSUE TITLE
Question - How to clear cache ?

### ISSUE THREAD

**Issue by kossa** [Arrilot/laravel-widgets#33]
Hi,

I want to use cache : https://github.com/arrilot/laravel-widgets#caching, and when I make some changes in DB I want to clear cache, is it possible ?

Thanks

**Comment by arrilot** [comment]
First of all , there is a `cacheKey()` method just as documentation states https://github.com/arrilot/laravel-widgets/blob/master/src/AbstractWidget.php#L74

Next you can use Laravel's `Cache::forget('key');` to remove the cache.
You are free to override `cacheKey()` method to make it easier for you to work with.

**Comment by arrilot** [comment]
In fact, we can also introduce cache tags in future releases. I'll leave it open for now.

**Comment by kossa** [comment]
Many thanks @arrilot :)

**Comment by arrilot** [comment]
Cache tags support landed there #101
