### ISSUE TITLE
Question - Howto set reload interval from config

### ISSUE THREAD

**Issue by ghermans** [Arrilot/laravel-widgets#35]
How can i assign a config var to reloadTimeout ?

i tried to set config('app.reload') to reloadTimeout, however this gives me the error.

```
FatalErrorException in RecentTasks.php line 25:
Constant expression contains invalid operations
```

**Comment by ghermans** [comment]
`public $reloadTimeout = Config::get('app.refreshInterval');`
is not working

**Comment by arrilot** [comment]
That is not a valid php. Assign it in constructor

**Comment by arrilot** [comment]
Do not forget to call parent::_construct

**Comment by ghermans** [comment]
Thanks for the response, adding it in a constructor did the trick.
