### ISSUE TITLE
How can I get all existing widgets list ?

### ISSUE THREAD

**Issue by tariqkhatri-gaditek** [Arrilot/laravel-widgets#4]
I have created 3 widgets for now, and I want to know dynamically (in controller) all the names of existing widgets,so that i can display their name. What is the possibility to do so ?

**Comment by arrilot** [comment]
There is no way to get list of  all widgets, it is such a weird use case.
If you really need to iterate through widget names - hardcode them or try to google how to get all class names from a selected namespace ('App/Widgets' by default)

**Comment by ArtemMolotov** [comment]
I want to add 'Role' middleware (check widget 'role' option and user role), but I can't get all widgets or all groupnames.
I think, it's necessary functionality.
