### ISSUE TITLE
contributing?

### ISSUE THREAD

**Issue by tfbenrowe** [Arrilot/laravel-widgets#40]
Whats your process for contributing new features/bugfixes? I've created my own `AbstractWidget` to resolve a couple of niggling issues I've dealt with which may be beneficial to the base package.

Are you happy to accept issues + approve + pull requests?

**Comment by arrilot** [comment]
Hi.
If you solved an issue and can make a PR - great. Just PR it.
If you have an idea/problem and can describe it - go ahead with an issue!
