### ISSUE TITLE
Inheritance config problem

### ISSUE THREAD

**Issue by benrowe** [Arrilot/laravel-widgets#42]
I'm creating a lot of widgets that extend from abstract widgets that i've created. The problem with this is because the config of a widget is stored under a single property `protected $config = []`, my concrete classes don't have an easy ability to set a base line config that inherits from the parent.

As a work around, i have to do something like this (crude example):

``` php
class MyListWidget extends BaseListWidget
{
    // can't declare property $config here otherwise it completely wipes out the base config

    public function __construct(array $config = [])
    {
        $defaults = [
          'classes' => 'base-list my-base-list'
        ];
        $this->config = array_merge($this->config, $defaults);
        parent::__construct($config);
    }
}

abstract class BaseListWidget extends Arrilot\Widgets\AbstractWidget 
{
    protected $config = [
      'data' => [],
      'classes' => 'base-list', 
    ];

    public function run()
    {
    }
}
```

This creates a lot of bootstrap to extend from the base config, and can create more problems with bigger inheritance chains (especially if you get the order of the merge mixed up..).

It would be better if each config option was a seperate public property. During the `constructor`, it would be quite easy to detect public properties and make those the `key` for the config. 

Because this would be fundamentally changing how the widgets set their config, you could prioritise `public properties` over the `config` property, thus maintaining backwards compatibility.

Additionally a convenience getter/setter makes the location of the config irrelevant.

Happy do submit a pull request if you think this is suitable.

**Comment by arrilot** [comment]
I understand your concerns

On the other hand we had public properties for each config key in the past and I wasn't quite happy with them because:
1. They bring boilerplate in another place - you need to define each class property and this is use case is much more widespread than your complex inheritance.
2. I want widget configuration to be separated from other propeties. It helps to avoid some edge cases too

**Comment by arrilot** [comment]
I've got an idea with changing `protected $config` to `private $defaults` but I need to do some testing first.

**Comment by arrilot** [comment]
Nope :(

This https://github.com/arrilot/laravel-widgets/commit/3a7a390d97fc7910f3b3734ca76b1f00c0512539 is the only thing I can do to make your life a little bit easier I'm afraid
