### ISSUE TITLE
Widget begin & end

### ISSUE THREAD

**Issue by benrowe** [Arrilot/laravel-widgets#43]
In addition to a `Widget::run()` which outputs a chunk of html to the view, a `Widget::begin()` & `Widget::end()` would be handy for encapsulating existing view logic, without the need to store that resulting logic into a variable.

For example:

``` php
{{ Widget::begin('Panel', ['title' => 'Foo', 'actions' => []]) }}
<h1>Content Title</h1>
{{ Widget::end() }}
```

Additionally you can wrap begin & end widgets recursively if needed.

I use this extensively in my own work and find it quite useful. Happy to submit a pull request.

**Comment by arrilot** [comment]
No plans to support this. Sorry.
Thanks for proposal though
