### ISSUE TITLE
Last release matcher is broken

### ISSUE THREAD

**Issue by matevisky** [Arrilot/laravel-widgets#50]
I was using the following widget configuration, and it has been broken on the last release:
`@widget('VideosWidget', ['type' => 'important', 'user' => auth()->user(), 'title' => 'Fontos videók az elmúlt 30 napból:)', 'days' => 30])
`
after fixing the :)' part, everything was working fine, guess the matcher is not working so well, or I do not know. Fixed code
`@widget('VideosWidget', ['type' => 'important', 'user' => auth()->user(), 'title' => 'Fontos videók az elmúlt 30 napból', 'days' => 30])
`

**Comment by arrilot** [comment]
It's a blade issue, not a package one.

`Blade::directive()` is used now https://github.com/arrilot/laravel-widgets/commit/c5e7d087ec21c784f2cf45442c14b0d7275ef148 and it's the official way to create custom directives.

**Comment by arrilot** [comment]
Blade uses regexpes under the hood. It tends to break when you start directly embedding complex strings with punctuation marks etc

**Comment by matevisky** [comment]
But in your last version you did overload that, and it was working like
charm..

**Comment by arrilot** [comment]
As you can see it had some issues too https://github.com/arrilot/laravel-widgets/pull/49

**Comment by matevisky** [comment]
ok, thx!
