### ISSUE TITLE
Can't do dependency injection

### ISSUE THREAD

**Issue by Photoshopper** [Arrilot/laravel-widgets#57]
I try to do dependency injection

```
private $categoriesMenuRenderer;

    public function __construct(CategoriesMenuRenderer $categoriesMenuRenderer)
    {
        parent::__construct();
        $this->categoriesMenuRenderer = $categoriesMenuRenderer;
    }
```

but I get an error

`Type error: Argument 1 passed to Modules\Articles\Http\Controllers\CategoriesMenu::__construct() must be an instance of Modules\Articles\Services\CategoriesMenuRenderer, array given`

I can't realise what am I doing wrong? In PublicController dependency injection works

**Comment by arrilot** [comment]
This is a constructor of a widget class right?
It's not resolved out of service container, you cant use DI there.

You can inject what you need into `run` method later

**Comment by Photoshopper** [comment]
Oh, thank you. You made my day
