### ISSUE TITLE
CacheKey

### ISSUE THREAD

**Issue by ahuggins** [Arrilot/laravel-widgets#58]
In the docs, it mentions that there is a cache key used that is based "on a widget name and each widget parameter" and digging in the code, it is not exactly clear what it is set to by default.

Is there a way to get an example for the RecentNews widget used throughout the docs?

Like if we want to clear the cache, do we do something like `Cache::forget('recentNews')`? Or is there something more it is based on?

`Cache::forget('arrilot.widgets.recentNews')`?

*\* Update...so digging in further, cause this is really interesting to me. You would have to do something like this:

`Cache::forget('arrilot.widgets.'serialize(['recentNews', ['count' => 5]])`

That seems to work (well, not 100% that, but something similar) for me in this project I am working on. Would be nice if we could set some simpler cache things that we could easily clear out cache for a widget. But there is a consideration of multiple templates using the widget in different ways, which is why you are serializing all the params instead of just the name. 

Like in one layout, you have ['count' => 5] and another one you have ['count' => 10']. These are different caches, and you wouldn't necessarily want to clear out both.

What about something like 

```
@widget('recentNews', ['count' => 5, 'cacheKey' => 'myUniqueKey']
```

Then in AbstractWidget.php

```
public function cacheKey(array $params = [])
    {
        // untested psuedo-code
        if(array_key_exists('cacheKey', $params[1])) {
                    return 'arrilot.widgets.'$params[1]['cacheKey']';
        }
        return 'arrilot.widgets.'.serialize($params);
    }
```

This (should) set the Cache key to `arrilot.widgets.myUniqueKey` that you could access anywhere. 

I'm open to some discussion on this, and would be willing to work on it, let me know your thoughts.

**Comment by arrilot** [comment]
In fact it's quore simply to adjust a cache key to your needs. Simply override cacheKey method in your widget with smth like this `return 'arrilot.widgets.recentNews.' . $this->config['cacheKey'];`

**Comment by arrilot** [comment]
I really really dont meant to make any of config keys specific. On the other hand I would be happy to accept a PR that adds done laravel's cache tags (see and other open issue) If your have enough passion

**Comment by arrilot** [comment]
I'm writting from a phone so sorry for typos. Hope you get the concept
