### ISSUE TITLE
Blade stack / push

### ISSUE THREAD

**Issue by ezstoritve** [Arrilot/laravel-widgets#59]
Hi,
i have a problem with stack and push directives. 
I have a page with header and directive @stack('css') in it. When i put a widget with @push('css') ... @endpush on a page nothing is reflected in @stack inside header. If @stack directive is put on a page after @widget directive, @push is reflected as supposed to.
So, if stack is before widget, nothing happens, if stack is after widget works as expected. 
What can i do to to solve the problem?

Thanks

**Comment by arrilot** [comment]
That's how Laravel's push/stack feature works.
You can test this behavior yourself in any blade file without any widgets involved
