### ISSUE TITLE
How to use it in Laravel 4

### ISSUE THREAD

**Issue by ghost** [Arrilot/laravel-widgets#6]
How to use it in Laravel 4 

I tried Docs code but it return as plain text

**Comment by arrilot** [comment]
Make sure that you use 1.0 branch and Blade syntax for L4
https://github.com/Arrilot/laravel-widgets/blob/1.0/README.md

**Comment by ghost** [comment]
Thanks for reply.
Thanks for Docs for L4. :+1: 

It Works.

**Comment by arrilot** [comment]
You are welcome.

**Comment by ghost** [comment]
I created my Widget in App\Widgets\MostPopular 

When i call it like {{ Widget::mostPopular() }} or {{ Widget::mostpopular() }}

It show error.
Class 'App\Widgets\MostPopular' not found'

I also create another Widget  App\Widgets\Cat 
 it works

**Comment by arrilot** [comment]
Try `composer dump-autoload`.

**Comment by ghost** [comment]
I tried again. It accepted now.

How to load Model in Widget?
