### ISSUE TITLE
Problem with @section

### ISSUE THREAD

**Issue by sklr** [Arrilot/laravel-widgets#60]
I have widget with:
...
return view("widgets.user_list");

user_list.blade.php extends another blade file(widget.blade.php) which has @yield('content') in it. 
The point is to make HTML wrapper for the widget. The HTML in widget.blade.php does not appear, I see only the actual widget file user_list.blade.php.

**Comment by arrilot** [comment]
I 've never supposed anyone to use it like that, but it surpisingly works as far as I can see

widget view:

``` php
@extends('minilayout')

@section('mini-content')
    data from widget in minicontent
@endsection
```

`minilayout.blade.php`

``` php
<strong>Mini-content: @yield('mini-content')</strong>
```

Main view that controller returns:

``` php
@extends('layout')

@section('content')
    @widget('recentNews')
@endsection
```

As a result I see "<strong>Mini-content:     data from widget in minicontent</strong>"
