### ISSUE TITLE
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by IncognitoCore** [Arrilot/laravel-widgets#62]
I am getting a PHP Fatal Error exception when running `php artisan make:widget RecentNews`, after going through the installation steps as described [here](https://github.com/arrilot/laravel-widgets).

`PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in .../vendor/laravel/framework/src/Illuminate/Container/Container.php on line 698`
`PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in .../vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 115`
_Full command output can be found as an attachment to this post._

Increase the value of xdebug.max_nesting_level in the php.ini (to 500, f.e.) did not help. It then told me it reached maximum function nesting level '500'.

`php artisan make:model test` runs without any issues.

I am running php 7.0.8-2+deb.sury.org~xenial+1 and using laravel 5.3.

What am I doing wrong? Or how can I solve this?
[PHP Fatal error.txt](https://github.com/arrilot/laravel-widgets/files/621453/PHP.Fatal.error.txt)

**Comment by arrilot** [comment]
Please make sure that you have the latest Laravel 5.3.*

**Comment by arrilot** [comment]
https://github.com/laravel/framework/issues/14950

**Comment by IncognitoCore** [comment]
Thanks for your reply! Fixed now:)

**Comment by StarNeit** [comment]
I got similar issue.

`PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /Volumes/Works/Web/Jiri3/ii_web_new/ii_web/vendor/laravel/framework/src/Illuminate/Container/Container.php:608
Stack trace:
#0 /Volumes/Works/Web/Jiri3/ii_web_new/ii_web/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('config', Array)
#1 /Volumes/Works/Web/Jiri3/ii_web_new/ii_web/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('config', Array)
#2 /Volumes/Works/Web/Jiri3/ii_web_new/ii_web/vendor/laravel/framework/src/Illuminate/Container/Container.php(1195): Illuminate\Foundation\Application->make('config')
#3 /Volumes/Works/Web/Jiri3/ii_web_new/ii_web/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(183): Illuminate\Container\Container->offsetGet('config')
#4 /Volumes/Works/Web/Jiri3/ii_web_new/ii_web/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(66): Illuminate\Auth\AuthManager->get in /Volumes/Works/Web/Jiri3/ii_web_new/ii_web/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 608`


How can I fix this error?

**Comment by StarNeit** [comment]
My laravel version is      "laravel/framework": "5.5.*"

**Comment by arrilot** [comment]
I've just checked it and I have no such error with latest laravel 5.5 and laravel-widgets.
I suppose the error lays in your app as described in the last post here https://github.com/laravel/framework/issues/14950
