### ISSUE TITLE
How to parse custom data.

### ISSUE THREAD

**Issue by gokhanyildiz** [Arrilot/laravel-widgets#65]
Hi, My english is a bit poor. I am sorry for this.
I do not have any problems viewing the parsing inside the blade file. But custom created variables not working.

MainNavigation Widget:

`<?php

namespace App\Widgets;

use Arrilot\Widgets\AbstractWidget;
use App\Module;

class MainNavigation extends AbstractWidget
{
    /**
     * The configuration array.
     *
     * @var array
     */
    protected $config = [];

    /**
     * Treat this method as a controller action.
     * Return view() or other content to display.
     */
    public function run()
    {
        $modules = Module::get();
        
        return view("widgets.main_navigation", [
            'navigation' => $modules,
        ]);
    }
}`

`Widget::run('mainNavigation', $navigation)`

main_navigation.blade.php

`dd($navigation)`

result

Undefined variable: navigation.

How can I solve this problem? Where am I doing wrong?

My laravel version: 5.3

Thanks.

**Comment by arrilot** [comment]
Can't replicate this. Looks like your code sample is incorrect.

Anyway, if you need to pass some data to `run()` directly you should pass it as 3rd arg.

E.g. `Widget::run('mainNavigation', [], $navigation)`
And then `public function run($navigation)`

**Comment by gokhanyildiz** [comment]
It not run again. I don't know where i'm doing wrong. For example, can you show me how to parse the config datas? I want to dynamically run widget data.

`{{ dd(App\Module::get()) }}`

This code works in main_navigation.blade.php. But I do not understand why it works when I send it variably.

Thanks for your help
