### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by trotsaleksandrov** [Arrilot/laravel-widgets#66]
Hello!
Are you going to release a new version which supports laravel 5.4?

**Comment by mbouclas** [comment]
Yeah, getting `Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found in vendor/arrilot/laravel-widgets/src/ServiceProvider.php on line 14
`

**Comment by arrilot** [comment]
Fixed in 3.7.0
