### ISSUE TITLE
Question: Call custom method of Widget class

### ISSUE THREAD

**Issue by sarfraznawaz2005** [Arrilot/laravel-widgets#67]
Thanks for very useful package !

I am writing a **widget that has dependent dropdowns** for country, state and cities. So if some country is selected, I want to be able to trigger an ajax request and get values for the states dropdown based on selected country. 

Now I can use normal LV controllers along with routes to send request and get list of states for the dropdown But is it possible to **create some method in my Widget class instead and that gets called via ajax to get some further data for the widget** ? The reason is that I want to have all relevant code of my widget in widget itself rather than doing this in normal LV controllers. So it boils down to how would you create a widget that has dependent dropdowns.

Thanks

**Comment by arrilot** [comment]
There is no way to call other widget methods.  

However you can pass some kind of flag via config array and make your `run` method look like

```php

public function run()
{
     switсh ($this->config['type']) {
            case 'country': 
               return $this->callCountryStuff();
            case ....
     }
}
```

Refs #27

**Comment by sarfraznawaz2005** [comment]
That should do the trick thanks
