### ISSUE TITLE
Dynamic Parameters

### ISSUE THREAD

**Issue by CrystalShardz** [Arrilot/laravel-widgets#69]
How can I add dynamic parameters to a widget?

My use case in this instance, is to create a tabbed widget where each tab reloads the widget content via AJAX and the data loaded (and the view displayed) will change in the widget dependant on which tab was clicked.

Thanks!

**Comment by arrilot** [comment]
This thread can probably help you https://github.com/arrilot/laravel-widgets/issues/67
