### ISSUE TITLE
Broken with latest BladeCompiler changes

### ISSUE THREAD

**Issue by webbie** [Arrilot/laravel-widgets#7]
With latest changes, `createMatcher()` is removed from Blade

```
FatalErrorException in ServiceProvider.php line 89:
Call to undefined method Illuminate\View\Compilers\BladeCompiler::createMatcher()
```

**Comment by arrilot** [comment]
Looks like you are using L5.1 which is not even close to being out.

**Comment by arrilot** [comment]
Anyway, i see nothing wrong in getting rid of those matchers right now.

Run composer update and you should be okay.

**Comment by webbie** [comment]
Well, I had `"laravel/framework": "~5.0"` in composer and looks like it installed `5.1-dev`. Need to doublecheck tomorrow.
Anyway, from what I know, 5.1 was scheduled for release in may.
