### ISSUE TITLE
show widgets outside of resources best practice

### ISSUE THREAD

**Issue by objectorientedninja** [Arrilot/laravel-widgets#72]
Hello, I'm using artem-schander/l5-modular so when I create a model it creates a views using this structure
    app/
    └── Modules/
        └── Testme/
            ├── Controllers/
            │   └── TestmeController.php
            ├── Models/
            │   └── Testme.php
            ├── Views/
            │   └── index.blade.php
            ├── Translations/
            │   └── en/
            │       └── example.php
            ├── routes
            │   ├── api.php
            │   └── web.php
            └── helper.php

I cant just use @widget('test') in my view because I get the following error?
Parse error: syntax error, unexpected 'echo' (T_ECHO) (View: C:\laragon\www\multiauth\app\Modules\Testme\Views\index.blade.php)
this is the problem view

@widget('testme')
echo trans('Testme::example.welcome');

**Comment by arrilot** [comment]
Looks like you have a php syntax error on the previous line (before `@widget`)

**Comment by objectorientedninja** [comment]
yeah It renders page fine with out widget but as soon as I add widget it breaks:) every thing in resources works perfect but I cant get a widget to work outside of that. I have tried apiato/apiato  and it works great outside of resources folder so I assume its a artem-schander/l5-modular issue. 
thank you!

**Comment by arrilot** [comment]
You can try to call a widget via facade 

`<?= Widget::run('testme') ?>`

That's the only advise a can give.
