### ISSUE TITLE
Question - How to get return data without HtmlString Object

### ISSUE THREAD

**Issue by workfredy** [Arrilot/laravel-widgets#73]
Hi all, I have a widget

`Widget::orderCountWidget(['itemID'=>1]);`

And the return result as below: 
```
Illuminate\Support\HtmlString Object
(
    [html:protected] => 0
)
```

How to return a result without HtmlString Object format, just return "` 0`"? Thank you

**Comment by vitalii-khr** [comment]
Hi,
You need to wrap this line using blade syntax {{ }}
`{{ Widget::orderCountWidget(['itemID'=>1]) }}`
or using PHP code:
`echo Widget::orderCountWidget(['itemID'=>1]);`

**Comment by arrilot** [comment]
If you need to get underlying string outside of blade file for some reason you can do the following:

```php
(string) Widget::orderCountWidget(['itemID'=>1]);
```

or

```php
Widget::orderCountWidget(['itemID'=>1])->toHtml();
```
