### ISSUE TITLE
Assets for widgets

### ISSUE THREAD

**Issue by lex111** [Arrilot/laravel-widgets#77]
Hello @arrilot,
Widgets often have their own styles and scripts. What are the ways to include them through this package? Considering the fact that the widget can be used many times, but its assets (styles, scripts) must be only included once.

**Comment by arrilot** [comment]
Hi, the package leaves this choice entirely to you. Most of the modern Laravel apps use elixir/mix from nodejs land to build assets. We can't hook into that anyway.

**Comment by lex111** [comment]
@arrilot well, I understand, but what are the solutions? Or did you use this use case?

I mean, as in Bitrix: there are files that automatically include: script.js and style.css. This is actual when you do not use Node.js to build assets.

**Comment by arrilot** [comment]
The simplest option is to create `resources/assets/sass|less|styles|whatever/widgets` and `resources/assets/js/widgets` directories, place your widgets assets inside them and add all this stuff into app.js and app.css using Laravel mix.

As a result you have all widgets assets available on every page
