### ISSUE TITLE
AJAX code - where to put this?

### ISSUE THREAD

**Issue by tochie-daniels** [Arrilot/laravel-widgets#78]
Hello,

The documentation did not say where to put the ajax/jquery code when using "asyncWidget()"  if I need to get some data from a server.

Looking at the JavascriptFactory, I found this - protected $ajaxLink = '/arrilot/load-widget'; 

Where can i declare my custom $ajaxLink?

**Comment by arrilot** [comment]
Hi. If you are using Async Widget you do not need to write any js/jquery code to load it. You don't need to register ajax route inside Laravel too.
The package does all this stuff for you. Just call 
`@asyncWidget('')` and you are done.

**Comment by tochie-daniels** [comment]
@arrilot 
Thanks for the response. You don't seem to get my issue. For example, I want to load news from an API server http://api-server.com. 
How and where do i access the returned data from - the widget class or inside the widget blade file?

**Comment by tochie-daniels** [comment]
Ok. I think I understand now. The ajax call is only meant to load the blade view. I need to make a call to the API from inside the widget class then pass the result to the blade view. Am i correct?

**Comment by arrilot** [comment]
> Am i correct?

Yes, that's one of the options.

Another one - write client-side ajax call in widget view (using javascript of course). 

It's up to you to decide which fits you better.
Hope that helps
