### ISSUE TITLE
Async Loading

### ISSUE THREAD

**Issue by jetwes** [Arrilot/laravel-widgets#8]
At first, thank you for this great package. It work's really well. How do i have to implement the async Loading in my view? If i use the AsyncWidget i only see the placeholder, my run ist never returned... What do i miss?

THanks
Jens

**Comment by arrilot** [comment]
Check Console and Network tabs in your chrome dev tools. 
Most likely you do not have jquery loaded before widget call and you will see some errors because of that.

Ajax request in the Network tab could help you to debug otherwise.

**Comment by jetwes** [comment]
Ok - jQuery is now loaded before - now i get a 500 on "/arrilot/async-widget" . Where do i have to define $ajaxLink?

**Comment by jetwes** [comment]
Got it. IN WidgetController you extend Controller - it has to be \Controller .... After changing this it worked...

**Comment by arrilot** [comment]
Should be fixed now (in 2.3.2)
