### ISSUE TITLE
Remove widget from group?

### ISSUE THREAD

**Issue by marktopper** [Arrilot/laravel-widgets#81]
Is it possible later to remove or disable a widget from a group?

**Comment by arrilot** [comment]
Hi Mark.
At the moment - No.
But it should be fairly easy to implement.

Could you describe your use case a little bit so we can be sure that future release actually helps with it?

:heart: your work on Voyager btw

**Comment by marktopper** [comment]
Hey arrilot.
Heh, thanks, funny thing, this is related to Voyager.
We use this package in Voyager, and are soon gonna release the ability to have plugins.
However some of the creators are gonna build plugins that add widgets by default to the admin panel of Voyager.
Therefor I would just love to add a feature for users to become able to disable some widgets without having to tell the plugin developer to setup a setting for whether or not they wish to have a widget.
Hope it make sense 👍

**Comment by arrilot** [comment]
Okay, here we go with the new release https://github.com/arrilot/laravel-widgets#removing-widgets-from-a-group
You need to update to the latest version (3.7.3) ofc. It's already tagged.
