### ISSUE TITLE
make:widget not generating empty view

### ISSUE THREAD

**Issue by GameFanager** [Arrilot/laravel-widgets#85]
Small issue as i can create the view myself, but it doesn't create the /resources/views/widgets folder or the empty view blade

Using Laravel 5.5 + laracogs fresh install

**Comment by arrilot** [comment]
Do you use default stub or your own? Have you checked linux permissions on view folder?

**Comment by GameFanager** [comment]
default stub, and tried with 777. Folder owner is correct as well.

**Comment by arrilot** [comment]
Thanks for reporting. I'll look into this issue closer once my vacation is over

**Comment by arrilot** [comment]
Okay. That's because of Laravel 5.5 breaking change in console commands, but I've just handled it.

You need to update to the latest version (3.7.5) ofc

**Comment by GameFanager** [comment]
Awesome thank you!
