### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::config()

### ISSUE THREAD

**Issue by nestor-developing** [Arrilot/laravel-widgets#86]
Hello

I have following error when running 'php artisan make:widget RecentNews' in Laravel 5.2

[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Illuminate\Console\GeneratorCommand::handle()

**Comment by arrilot** [comment]
Hi, do you use the latest version (3.7.5)? If that's the case could you please rollback to 3.7.4 to see if fixes the problem

**Comment by arrilot** [comment]
Fixed in 3.7.6
