### ISSUE TITLE
Return Either a View or A Response

### ISSUE THREAD

**Issue by codeitlikemiley** [Arrilot/laravel-widgets#89]
Well there are instances that we dont want to use Laravel Blade to Create Widgets.
Im Using Vue Js , and im using vue components for widgets...
But It Would Make sense if we can use this package to pre-populate the components initial state or data.
in my vue Project i have a Global initial state provider.
i can easily add a widget object to be return there...
but of course instead of returning a view i want to return a reponse, where i can specify , my own css class.
to make it data driven... 

we can do something like this

```
public function responsable()
    {
        return $this->users;
    }
     
    public function renderable()
    {
        return view('users.index', ['users' => $this->users]);
    }
```

by default 
Widget::recentNews() or Widget::recentNews()->renderable()

would return the view template

but if we chain something like this, Widget::recentNews()->responsable()

would return a json response instead...

**Comment by codeitlikemiley** [comment]
More or less something like this...
https://johannespichler.com/using-laravels-responsable-interface

**Comment by arrilot** [comment]
So, basically you need a way to return json instead of a view in some cases, right?
It should be not that hard to achieve using inheritance.

```php
class AbstractRecentNewsWidget extends AbstractWidget
{
   public function run()
   {
      // all the logic here

      return $someDataAsArrayOrObject;
   }
}
```

```php
class RecentNews extends AbstractRecentNewsWidget
{
   public function run()
   {
      return view('recent_news.index', ['data' => parent::run()]);
   }
}
```

```php
class RecentNewsJson extends AbstractRecentNewsWidget
{
   public function run()
   {
       return parent::run(); // or json_encode(parent::run()), not sure
   }
}
```

And then all you need is to swap `Widget::recentNews()` with `Widget::recentNewsJson()` if you need the json form

**Comment by tomhatzer** [comment]
You could also just pass the Accept header with your request e.g. `Accept: application/json` and laravel will return json instead of your defined view.

**Comment by codeitlikemiley** [comment]
thanks for suggestions ill try it
