### ISSUE TITLE
@push to a @stack

### ISSUE THREAD

**Issue by nasirkhan** [Arrilot/laravel-widgets#90]
Is there any way to use `@push` for a `@stack` of the application layout? 

I was using the widget to add a map on the page. I want to `@push` map related CSS and JS files to the Javascript `@stack` of my blade layout. What is the right way to doing so ?

**Comment by arrilot** [comment]
I'm not 100% sure, but `@push` should work just like in any other blade view.

May this be your issue #59?

**Comment by nasirkhan** [comment]
@arrilot Thanks for your response. 

#59 is kind of similar but not the same. 

I wanted to push CSS as JS libraries and JS configs from the Widget Blade. The time i posted this issues it was not working for my mistake. but it works perfectly. I think you should mention this in the doc. actually i posted the issue as i did not find anything on the doc.
