### ISSUE TITLE
Send Parameters through ajax

### ISSUE THREAD

**Issue by GeoSot** [Arrilot/laravel-widgets#91]
Hello, arrilot. You package is great.

I have two questions, i may didn't find on my search of solved issues.

Can i use ajax request in order to reload a widget but with some different parameters?

And as i saw the params are encrypted.  Can you propose me  a way to encrypt parameters using js, or can i use parameters without encryption?

**Comment by arrilot** [comment]
Hi

> Can i use ajax request in order to reload a widget but with some different parameters?

Unfortunately, It's possible only if you code this ajax request by yourself.

> Can you propose me a way to encrypt parameters using js?

The package uses Laravel's build-in encryptor.
https://github.com/arrilot/laravel-widgets/blob/master/src/Factories/AbstractWidgetFactory.php#L168
There is no way to mimic its behaviour in js, as far as I know. You can try to do it in php though and then send already encrypted value to frontend via ajax call or directly from a view.

> Can i use parameters without encryption?

At the moment - no. But thats a decent idea, and I think it will make its way to the next release.
You can try to send ajax request to another endpoint (not `arrilot/load-widget`) for now and handle it like this https://github.com/arrilot/laravel-widgets/blob/master/src/Controllers/WidgetController.php but skipping decryption step

**Comment by GeoSot** [comment]
Your last proposal seems feasibly . Thank you a lot.

**Comment by arrilot** [comment]
Addressed in a 3.8.0 release

>Widget params are encrypted (by default) and sent via ajax call under the hood. So expect them to be json_encoded() and json_decoded() afterwards.

>Note: You can turn encryption off for a given widget by setting public $encryptParams = false; on it. However, this action makes widget params publicly accessible, so please make sure you do not leave any vulnerabilities. For example, if you pass something like user_id through widget params and turn encryption off, you do need to add one more access check inside the widget.
