### ISSUE TITLE
Laravel Recently Viewed Products with Widget

### ISSUE THREAD

**Issue by donatiss** [Arrilot/laravel-widgets#97]
Hello, i'm trying to create Laravel Recently Viewed Products with this Widgets package, can you tell me, is it everything okey? I'm not sure about addProduct function. I'm new on Laravel so sorry, if it is stupid question :)

`<?php

namespace App\Widgets;

use Arrilot\Widgets\AbstractWidget;
use App\Models\Product;

class RecentlyViewedProducts extends AbstractWidget {

    protected $config = [
        'items' => [],
        'item' => null
    ];

    protected $session_key = 'products.recently_viewed';

    protected $show = 4;

    public function run()
    {
        if (!is_null($this->config['item'])) $this->addProduct($this->config['item']);

        return view('widgets.recently_viewed_products', [
            'config' => [
                'items' => $this->getProducts()
            ],
        ]);
    }

    private function addProduct($id) {
        //session()->forget($this->session_key);

        $product = Product::where('id', $id)->with('images')->firstOrFail();
        $products = $this->getProducts();

        if (session()->has($this->session_key)) {
            foreach($products as $index => $item) {
                $exist = false;

                if ($product->id == $item->id) {
                    $exist = true;

                    break;
                }
            }
            if (!$exist) session()->push($this->session_key, $product);
        } else {
            session()->push($this->session_key, $product);
        }

        if (count($products) > $this->show && !$exist) {
            $array = session()->pull($this->session_key, []);
            unset($array[min(array_keys($products))]);
            session()->put($this->session_key, $array);
        }
    }

    private function getProducts() {
        return session()->get($this->session_key);
    }
}
`
blade file:
`@extends('website.layouts.main')

@section('content')
    ...
@endsection

@section('bottom_content')
    @widget('recently-viewed-products', ['item' => $result->id])
@endsection`

**Comment by arrilot** [comment]
Best practise: your widget should have only one responsibility - show products extracted from session, you shouldn't add them there.

You'd better add a new product to session somewhere in controller action for its detail page.
