### ISSUE TITLE
Caching vs Multilang

### ISSUE THREAD

**Issue by ToeiRei** [Arrilot/laravel-widgets#99]
1. Use `@lang('lang.text')` in a widget. 
2. Switch language.

Switching languages will work on anything but the widget.

**Comment by arrilot** [comment]
Hi. that's because Laravel's locale is not included in cache key by default.

You can either 
override the `cacheKey()` method of widget/widgets 
or 
simply add `'locale' => app()->getLocale()` to config array when you call a widget (all config values are included in cache key(

**Comment by ToeiRei** [comment]
I was trying to set `public $cacheTime = false;` which I was expecting to solve the problem - but that wasn't the case.

Your solution, adding the locale to the config always gives "Constant expression contains invalid operations" - as it's protected.

**Comment by ToeiRei** [comment]
Digging deeper I found out that the session isn't available in the widget - that's what messes up my widgets. So I think I have to pull things in as a parameter.
